### ISSUE TITLE
Distance calculation

### ISSUE THREAD

**Issue by imbalu007** [ritheshkumar95/pytorch-vqvae#15]
Can you please explain how you are computing the distance between the codebook and inputs? In `functions.py`, you are using this line:
`distances = torch.addmm(codebook_sqr + inputs_sqr, inputs_flatten, codebook.t(), alpha=-2.0, beta=1.0)`

I am unable to understand how this will give the euclidean distance between inputs and codebook.

**Comment by tristandeleu** [comment]
This is using the decomposition `(codebook - inputs)^2 = codebook^2 + inputs^2 - 2 * codebook * inputs`. See the [`torch.addmm`](https://pytorch.org/docs/master/generated/torch.addmm.html) documentation for the order of the arguments (which is a bit misleading).

Computing the distance this way avoids the creation of a (possibly very large) intermediate matrix `codebook - inputs`, so that you can fit larger inputs / codebooks on the GPU.

**Comment by Roller44** [comment]
How about using [`torch.cdist`](https://pytorch.org/docs/stable/generated/torch.cdist.html)?
